[package]
name = "pallet-coming-id-rpc-runtime-api"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "RPC runtime API for transaction payment FRAME pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { version = "3.0.0", default-features = false, path = "../../../../../../primitives/api" }
sp-std = { version = "3.0.0", default-features = false, path = "../../../../../../primitives/std" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
pallet-coming-id = { version = "1.0.0", default-features = false, path = "../../../pallet-coming-id" }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"sp-std/std",
	"codec/std",
	"pallet-coming-id/std",
]
