[package]
authors = ['Minix Chain Developer']
edition = '2018'
name = 'pallet-coming-id'
version = "1.0.0"
license = "Unlicense"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.119", optional = true }
frame-support = { default-features = false, version = "3.0.0", path = "../../../../frame/support" }
frame-system = { default-features = false,  version = "3.0.0",  path = "../../../../frame/system" }
frame-benchmarking = { default-features = false,  version = "3.1.0",  path = "../../../../frame/benchmarking", optional = true }
sp-runtime = { default-features = false, version = "3.0.0", path = "../../../../primitives/runtime" }
sp-std = { default-features = false, version = "3.0.0", path = "../../../../primitives/std" }
sp-core = { default-features = false, version = "3.0.0", path = "../../../../primitives/core" }
hex-literal = { version = "0.3.1", optional = true }
log = { version = "0.4.14", default-features = false }

[dev-dependencies]
serde = { version = "1.0.119" }
sp-core = { default-features = false, version = "3.0.0", path = "../../../../primitives/core" }
sp-io = { default-features = false, version = "3.0.0", path = "../../../../primitives/io" }
sp-runtime = { default-features = false, version = "3.0.0", path = "../../../../primitives/runtime" }
hex-literal = { version = "0.3.1"}

[features]
default = ['std']
std = [
	'codec/std',
	'serde/std',
	'log/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	'sp-runtime/std',
	'sp-std/std',
	'sp-core/std'
]

runtime-benchmarks = [
	"frame-benchmarking",
	"hex-literal"
]

try-runtime = ["frame-support/try-runtime"]
