[workspace]
resolver = "2"

members = [
	"node",
	"runtime",

	"pallets/pallet-coming-id",
	"pallets/pallet-coming-nft",
	"pallets/ethereum-chain-id",
	"pallets/custom-signatures",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
