[workspace]
resolver = "2"

members = [
	"bin/minix/node",
	"bin/minix/pallets/pallet-coming-id",
	"bin/minix/pallets/pallet-coming-nft",
	"bin/minix/pallets/pallet-coming-auction",
	"bin/minix/runtime",
]

exclude = [
	"bin/node",
	"bin/utils",
	"client",
	"docs",
	"frame",
	"keystore",
	"primitives",
	"test",
	"test-utils",
	"utils"
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
