[workspace]
resolver = "2"

members = [
    "node",
    "runtime",

    "pallets/deposit",
    "pallets/pallet-coming-id",
    "pallets/pallet-coming-nft",
    "pallets/pallet-coming-auction",
    "pallets/ethereum-chain-id",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
