[package]
edition = '2018'
name = 'pallet-commodities'
version = '1.0.0'
authors = ['Dan Forbes <dan@parity.io>']
license = 'Unlicense'
description = 'A unique asset (NFT) interface and a Substrate FRAME implementation optimized for commodity assets.'
homepage = 'https://github.com/danforbes/pallet-nft'
repository = 'https://github.com/danforbes/pallet-nft'
readme = 'README.md'
keywords = ['substrate', 'frame', 'nft', 'blockchain', 'asset']
categories = ['cryptography::cryptocurrencies', 'data-structures', 'no-std']

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
serde = { version = "1.0.116", optional = true }

# Substrate dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
frame-support = { default-features = false, version = '3.0.0', path = "../../../../frame/support" }
frame-system = { default-features = false, version = '3.0.0', path = "../../../../frame/system" }
sp-runtime = { default-features = false, version = '3.0.0', path = "../../../../primitives/runtime" }
sp-std = { default-features = false, version = '3.0.0', path = "../../../../primitives/std" }

[dev-dependencies]
sp-core = { default-features = false, version = '3.0.0', path = "../../../../primitives/core" }
sp-io = { default-features = false, version = '3.0.0', path = "../../../../primitives/io" }

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-std/std',
]
