[package]
authors = ['Minix Chain Developer']
edition = '2018'
name = 'pallet-coming-auction-rpc-runtime-api'
version = "1.2.0"
license = "Unlicense"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { version = "3.0.0", default-features = false, path = "../../../../../../primitives/api" }
sp-std = { version = "3.0.0", default-features = false, path = "../../../../../../primitives/std" }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../../../../../primitives/runtime" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
pallet-coming-auction = { version = "1.2.0", default-features = false, path = "../../../pallet-coming-auction" }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"sp-std/std",
	"sp-runtime/std",
	"codec/std",
	"pallet-coming-auction/std",
]
