[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
edition = '2018'
name = 'pallet-coming-id'
version = "1.0.0"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
description = "FRAME pallet template for defining custom runtime logic."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.119", optional = true }
frame-support = { default-features = false, version = "3.0.0", path = "../../../../frame/support" }
frame-system = { default-features = false,  version = "3.0.0",  path = "../../../../frame/system" }
frame-benchmarking = { default-features = false,  version = "3.1.0",  path = "../../../../frame/benchmarking", optional = true }
sp-runtime = { default-features = false, version = "3.0.0", path = "../../../../primitives/runtime" }
pallet-sudo = { default-features = false, version = "3.0.0", path = "../../../../frame/sudo"}

[dev-dependencies]
serde = { version = "1.0.119" }
sp-core = { default-features = false, version = "3.0.0", path = "../../../../primitives/core" }
sp-io = { default-features = false, version = "3.0.0", path = "../../../../primitives/io" }
sp-runtime = { default-features = false, version = "3.0.0", path = "../../../../primitives/runtime" }

[features]
default = ['std']
std = [
	'codec/std',
	'serde/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	'sp-runtime/std',
	'pallet-sudo/std'
]

runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
