[package]
name = "pallet-talent-contract"
version = "0.1.0"
authors = ["icodezjb"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.119", optional = true }
log = { version = "0.4.14", default-features = false }
frame-support = { default-features = false, version = "3.0.0", path = "../../../../frame/support" }
frame-system = { default-features = false,  version = "3.0.0",  path = "../../../../frame/system" }
sp-runtime = { default-features = false, version = "3.0.0", path = "../../../../primitives/runtime" }
sp-std = { default-features = false, version = "3.0.0", path = "../../../../primitives/std" }
sp-core = { default-features = false, version = "3.0.0", path = "../../../../primitives/core" }

[dev-dependencies]
serde = { version = "1.0.119" }
sp-io = { default-features = false, version = "3.0.0", path = "../../../../primitives/io" }
sp-runtime = { default-features = false, version = "3.0.0", path = "../../../../primitives/runtime" }
hex-literal = { version = "0.3.1"}

[features]
default = ['std']
std = [
    'codec/std',
    'serde/std',
    'log/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-std/std',
    'sp-core/std'
]
